name: Link to asana task

on:
  pull_request:
    types: [opened]

jobs:
  link-to-asana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ../..
        with:
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          task-comment: 'PR: <a href="$PR_URL">$PR_TITLE</a>'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
